### ISSUE TITLE
不支持脚注

### ISSUE THREAD

**Issue by allinprogram** [guqing/willow-mde#1]
如题，请问有适配的计划吗？这应该是标准语法。

**Comment by guqing** [comment]
https://github.com/guqing/willow-mde/commit/4c73eef087f18aee3d82ba60eae7beda0fc8c0e5 在最新的提交已经支持了，commonMark 规范并不支持脚注和表格所以支持了gfm，不过编辑器的脚注和表格预览等还没有支持还需要进一步完善

**Comment by allinprogram** [comment]
Thank you for everything.

**Comment by guqing** [comment]
表格和脚注支持已经发布到应用市场 1.0.0-beta.2 版本：[halo.run/store/apps/app-kqZUw?tab=releases](https://www.halo.run/store/apps/app-kqZUw?tab=releases)
