### ISSUE TITLE
表格不支持，希望添加

### ISSUE THREAD

**Issue by GD2021** [guqing/willow-mde#10]
原文markdown：

## 常规设置

在该设置项里，仅需要设置一下使用 `过滤器和 Hosts 文件拦截指定域名`。该配置项规定了更新过滤器的时间，通常我们认为 24 小时是一个合理的区间，您可以根据自己的需求进行增大或者缩小。

剩下的安全搜索，家长控制，浏览安全，则是没有必要的功能，因为境内使用体验不佳。

关于日志，您需要根据您的存储空间大小来选择一个比较合理的区间，举个例子：

| 通常设备类型 | 通常存储大小 | 建议日志保留时间 |
| --- | --- | --- |
| 小存储设备 | 256 MiB / 512 MiB / etc. | 建议日志不要过大，建议只保留一天 |
| 服务器 | \> 10 Gib | 根据您的存储使用情况，可以七天以上，我个人选择直接保留 90 天 |

被忽略的网域选项：它适用于大量无用查询的情况。举个例子，如果您通过查询日志发现有大量的 `dataflow.biliapi.com` 查询，这些查询是无用的，并且会占用日志空间，那么您可以将其添加到忽略网域列表中，以减少日志空间的浪费。

预览：
![image](https://github.com/guqing/willow-mde/assets/81171294/83e5d7f6-1cee-4109-a16f-fc8889a81865)

在其他在线markdown显示：
![image](https://github.com/guqing/willow-mde/assets/81171294/dc4cd48f-9da5-492f-a8df-e30356d5d7b5)

**Comment by guqing** [comment]
你是用的版本是什么呢

**Comment by guqing** [comment]
如果没有后续反馈我就先关闭了，如果有问题随时打开
