### ISSUE TITLE
选中code区域无法高亮显示

### ISSUE THREAD

**Issue by adozhao** [guqing/willow-mde#11]
新增文章时，想要滑动复制代码区域，实际上滑动选择和复制是没问题的，但是选中区域无法高亮显示
插件版本：1.0.0-beta.2
halo版本：2.11.2
chrome版本：119.0.6045.200（正式版本） （64 位）

![image](https://github.com/guqing/willow-mde/assets/23180747/3c993869-c0cf-430e-80de-4f3ea94aea87)

**Comment by guqing** [comment]
代码块加上语言了吗？
<img width="506" alt="image" src="https://github.com/guqing/willow-mde/assets/38999863/ea1c0626-021d-418d-a920-cfefb90548d5">

**Comment by github-ayio** [comment]
没加 @guqing

**Comment by guqing** [comment]
感谢反馈，刚刚理解错意思了 😀

**Comment by guqing** [comment]
试了一下，这个问题看起来很简单但是由于 codemirror 的选中设计问题我发现暂时无法解决这个样式问题，先等等吧
