### ISSUE TITLE
markdown表格遇到无法被渲染的问题

### ISSUE THREAD

**Issue by HoronLee** [guqing/willow-mde#6]
https://blog.horonlee.com/archives/openstackyun-wei-bi-ji
此文章的`安装openstack`标题下的表格，使用的主题是Halo
```
| 组件名称 | Controller | Compute | 作用 |
| :-------- | :--------: | :-----: | :------: |
| Keystone | √ | × | 身份验证 |
| Glance | √ | × | 镜像管理 |
| Placement | √ | × | 放置服务 |
| Nova | √ | √ | 计算服务 |
| Neutron | √ | √ | 网络服务 |
| Dashboard | √ | × | 管理面板 |
```

**Comment by guqing** [comment]
已在 main 分支修复晚点会发个版本🌟

相关问题：https://github.com/guqing/willow-mde/issues/1#issuecomment-1767561233

**Comment by guqing** [comment]
已经发布到应用市场：[halo.run/store/apps/app-kqZUw?tab=releases](https://www.halo.run/store/apps/app-kqZUw?tab=releases)
