### ISSUE TITLE
markdown表格无法渲染

### ISSUE THREAD

**Issue by manman-dong** [guqing/willow-mde#8]
编辑器里面的表格预览不能正常工作， 预览结果如图所示，我换了三四个主题，换了使用chrome和edge浏览器都是这样显示，另外一个编辑器《StackEdit》预览下可以正常显示表格

![](https://blog.wohaoxiangxiaohhh.top/upload/iShot_2023-11-16_00.51.20.png)

**Comment by guqing** [comment]
duplicate with #7

已经修复稍后我会发布一个版本

**Comment by manman-dong** [comment]
好的，感谢大佬

**Comment by guqing** [comment]
已经发布到应用市场：https://www.halo.run/store/apps/app-kqZUw?tab=releases

**Comment by manman-dong** [comment]
看见了，已经更新，问题已解决。大佬威武！
