### ISSUE TITLE
在Halo的目录无法跳转至网页适当位置

### ISSUE THREAD

**Issue by xyblue135** [guqing/willow-mde#9]
使用此编辑器编辑的目录无法跳转至具体位置，点击任意一个返回顶部，使用的halo，默认主题和其它主题都有这样的情况
![ERROT](https://github.com/guqing/willow-mde/assets/127581667/76137ea6-838c-45a1-ad65-95b3dfaeab80)

**Comment by guqing** [comment]
感谢反馈

**Comment by lxz946786639** [comment]
没有下文了吗 0 0

**Comment by guqing** [comment]
> 没有下文了吗 0 0

sorry 我都忙忘了😃，已经修复了 我一会儿先发个版

**Comment by guqing** [comment]
已经发布到应用市场了，https://www.halo.run/store/apps/app-kqZUw?tab=releases，更新后以前不生效的文章需要重新发布

**Comment by lxz946786639** [comment]
> 已经发布到应用市场了，https://www.halo.run/store/apps/app-kqZUw?tab=releases ，更新后以前不生效的文章需要重新发布

感谢感谢，厉害

**Comment by xyblue135** [comment]
感谢！
